import './globals.css'
import { Inter } from 'next/font/google'
import { Plus_Jakarta_Sans } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const Jakarta = Plus_Jakarta_Sans({
  weight: ['200','300','400', '500', '600', '700', '800'],  
  subsets: ['latin'],
})

export const metadata = {
  title: 'Dashboard: Overview | Devias Kit PRO',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Jakarta.className}>
        {children}
        </body>
    </html>
  )
}
